[package]
name = "hyprland-workspaces"
version = "1.0.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.8", features = ["derive"] }
hyprland = "0.4.0-alpha.2"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
